/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package viewer;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;

/**
 *
 * @author Aurelia
 */
public class GamePanel extends javax.swing.JPanel {
    
    private static final int defWidth = 800;
    private static final int defHeight = 600;
    private int timerDelay;
    private final Timer timer;

    /**
     * Creates new form GamePanel
     */
    public GamePanel() {
        super();
        this.setPreferredSize(new Dimension(defWidth, defHeight));
        this.setVisible(true);
        this.setBackground(Color.BLACK);
        timerDelay = 1000;
        timer = new Timer(timerDelay, gameTimer);
        timer.start();
        
    }
    
    public void paintComponent(Graphics graphics) {
        super.paintComponent(graphics);
        graphics.setColor(Color.red);
        graphics.drawRect(10, 10, 10, 10);
    }
    
    public void redraw() {
        this.repaint();
        System.out.println("Screen has been redrawn.");
    }
    
    ActionListener gameTimer = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
            redraw();
        }
    };

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
